<?php if (isset($readonly)): ?>
  <div class="form-inline <?php echo isset($disabled) ? 'muted' : '' ?>">
<?php else: ?>
  <form name="rule"
    action="<?php echo $app->urlFor($rule->id ? 'http_rules.update' : 'http_rules.create', array('id' => $rule->id)) ?>" 
    method="post" class="form-inline">
<?php endif ?>

  <?php if (!isset($readonly)): ?>
    <input type="hidden" name="owner_type" value="<?php echo $rule->owner_type ?>">
    <input type="hidden" name="owner_id" value="<?php echo $rule->owner_id ?>">
  <?php endif ?>

  <?php if ($rule->id && !isset($readonly)): ?>
    <span class="control-group sortable-handle" title="Drag to change position" style="padding: 5px; margin-right: 10px">
      <i class="icon-move"></i>
    </span>
  <?php endif ?>

  <span class="control-group <?php echo isset($errors['address']) ? 'error' : '' ?>">
    <?php if (isset($readonly)): ?>
      <span class="input input-xlarge"><?php echo h($rule->address) ?></span>
    <?php else: ?>
      <input type="text" name="address" placeholder="Domain or IP" 
        value="<?php echo isset($errors['address']) ? $errors['address'] : $rule->address ?>" 
        class="input-xlarge" 
        required
        <?php echo isset($errors['address']) ? 'autofocus' : '' ?>>
    <?php endif ?>
  </span>

  <span class="control-group">
    <?php if (isset($readonly)): ?>
      <span class="input input-small"><?php echo $rule->allow ? 'Allow' : 'Deny' ?></span>
    <?php else: ?>
      <select name="allow" class="input-small">
        <option value="1" <?php echo $rule->allow ? 'selected' : '' ?>>Allow</option>
        <option value="0" <?php echo $rule->allow ? '' : 'selected' ?>>Deny</option>
      </select>
    <?php endif ?>
  </span>

  <span class="control-group">
    <?php if (isset($readonly)): ?>
      <span class="input">
        <i class="icon-<?php echo $rule->http ? 'ok' : 'remove' ?>"></i> HTTP
        <i class="icon-<?php echo $rule->https ? 'ok' : 'remove' ?>"></i> HTTPS
      </span>
    <?php else: ?>
      <label for="http-<?php echo $rule->id ?>" class="checkbox">
        <input type="checkbox" name="http" value="1" 
          <?php echo $rule->http ? 'checked' : '' ?> id="http-<?php echo $rule->id ?>">
        HTTP
      </label>
      <label for="https-<?php echo $rule->id ?>" class="checkbox">
        <input type="checkbox" name="https" value="1" 
          <?php echo $rule->https ? 'checked' : '' ?> id="https-<?php echo $rule->id ?>">
        HTTPS
      </label>
    <?php endif ?>
  </span>

  <?php if (!isset($readonly)): ?>
    <span class="control-group" style="margin-left: 10px">
      <?php if ($rule->id): ?>
        <button name="update" type="submit" class="btn btn-primary btn-small" title="Save changes">Save</button>
        <a data-action="rules.remove" data-confirm="Are you sure you want ot delete this rule?"
          href="<?php echo $app->urlFor('http_rules.delete', array('id' => $rule->id)) ?>"
          title="Delete rule" 
          class="btn btn-small btn-danger" style="margin-left: 10px"><i class="icon-remove"></i></a>
      <?php else: ?>
        <button name="create" type="submit" class="btn btn-primary btn-small" title="Create rule">Create</button>
        or <a href="#" data-action="rules.cancel">Cancel</a>
      <?php endif ?>
    </span>
  <?php endif ?>

  <?php partial('_inline_flash.phtml', array('flash' => $flash)) ?>

<?php if (isset($readonly)): ?>
  </div>
<?php else: ?>
  </form>
<?php endif ?>
