<div class="rules">
  <ul class="unstyled">
    <?php foreach ($rules as $rule): ?>
    <li>
      <?php partial('rules/_http_form.phtml', array('rule' => $rule)) ?>
    </li>
    <?php endforeach ?>
  </ul>

  <div class="new-rule" style="display: none">
    <?php partial('rules/_http_form.phtml', array('rule' => new HTTPAccessRule(array(
      'owner_type' => $rule_owner_type,
      'owner_id' => $rule_owner_id
    )))) ?>
  </div>

  <a data-action="rules.define" href="#" class="btn btn-success">Define rule</a> 
</div>


