<?php if ($user->is_member()): ?>
  <div class="form-inline">
    Default rule policy:
    <strong class="input input-small">
      <?php echo $user->group->default_policy ? 'Allow' : 'Deny' ?></span>
    </strong>
    <span class="muted">
      (set by group <?php echo h($user->group->name) ?>)
      <a href="<?php echo $app->urlFor('groups.show', array('id' => $user->group_id)) ?>#openvpn-settings"
         class="btn btn-mini" title="Edit group settings"><i class="icon-edit"></i></a>
    </span>
  </div>

<?php else: ?>
  <form class="form-inline" method="post"
        action="<?php echo $app->urlFor('users.default_policy', array('id' => $user->id)) ?>"
        style="margin-bottom: 0">
    <label for="default-policy">Default rule policy: </label>
    <select name="default_policy" class="input-small" data-action="ovpn.setDefaultPolicy">
      <option value="1" <?php echo $user->default_policy == 1 ? 'selected' : '' ?>>Allow</option>
      <option value="0" <?php echo $user->default_policy == 0 ? 'selected' : '' ?>>Deny</option>
    </select>
  </form>

  <?php partial('_inline_flash.phtml', array('flash' => $flash)) ?>
<?php endif ?>
