<?php if ($user->is_member()): ?>
  <div class="form-inline well well-small">
    <span class="input checkbox"> 
     <i class="icon-<?php echo $user->group->redirect_all_traffic ? 'ok' : 'remove' ?>"></i> 
      Redirect all user traffic through VPN 
      (set by group <?php echo h($user->group->name) ?>)
      <a href="<?php echo $app->urlFor('groups.show', array('id' => $user->group_id)) ?>#openvpn-settings"
         class="btn btn-mini" title="Edit group settings"><i class="icon-edit"></i></a>
    </span>
  </div>

<?php else: ?>
  <form class="form-inline well well-small" method="post"
        action="<?php echo $app->urlFor('users.redirect_all_traffic', array('id' => $user->id)) ?>">
    <label class="checkbox">
      <input type="checkbox" value="1" name="redirect_all_traffic"
          <?php echo $user->redirect_all_traffic ? 'checked="checked"' : '' ?>
          data-action="ovpn.setRedirectAllTraffic">
      Redirect all user traffic through VPN
    </label>
  </form>

  <?php partial('_inline_flash.phtml', array('flash' => $flash)) ?>
<?php endif ?>
