<?php if ($user->suspended): ?>
  <a href="<?php echo $app->urlFor('users.toggle_suspend', array('id' => $user->id)) ?>" 
     data-action="users.toggleSuspend" class="btn btn-success">
  <i class="icon-ok-sign icon-white"></i> Unsuspend access
</a>
<?php else: ?>
  <a href="<?php echo $app->urlFor('users.toggle_suspend', array('id' => $user->id)) ?>"
     data-action="users.toggleSuspend" class="btn btn-danger">
    <i class="icon-ban-circle icon-white"></i> Suspend access
  </a>
<?php endif ?>

<?php partial('_inline_flash.phtml', array('flash' => $flash)) ?>

