<h3>List of users</h3>

<table class="table  table-condensed table-hover">
  <thead>
    <tr>
      <th style="width: 8%">#</th>
      <th style="width: 30%">Username</th>
      <th style="width: 50%">Fullname</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
    <tr>
      <td>1</td>
      <td>@mdo</td>
      <td>Mark Otto</td>
      <td>
        <button class="btn btn-small">Edit</button>
        <button class="btn btn-small btn-danger">Delete</button>
      </td>
    </tr>
  </tbody>
</table>
