<ul class="breadcrumb">
  <li><a href="<?php echo $app->urlFor('users') ?>">Users</a> <span class="divider">/</span></li>
  <li><a href="<?php echo $app->urlFor('users.new') ?>">Add user</a></li>
</ul>

<div class="page-header">
  <h3>Add new user</h3>
</div>

<form class="form-horizontal" action="<?php echo $app->urlFor('users.create') ?>" method="post">
  <?php partial('_form_errors.phtml', array('errors' => $errors)) ?>

  <div class="control-group">
    <label class="control-label" for="user-username">Username</label>
    <div class="controls">
      <input name="username" type="text" id="user-username" value="<?php echo $user->username ?>">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="user-fullname">Fullname</label>
    <div class="controls">
      <input name="fullname" type="text" id="user-fullname" value="<?php echo $user->fullname ?>">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>
