<ul class="breadcrumb">
  <li><a href="<?php echo $app->urlFor('users') ?>">Users</a> <span class="divider">/</span></li>
  <li><a href="<?php echo $app->urlFor('users.show', array('id' => $user->id)) ?>"><?php echo h($user->username) ?></a></li>
</ul>

<div class="page-header">
  <h3><?php echo h($user->username) ?> <small><?php echo h($user->fullname) ?></small></h3>
</div>

<form class="form-inline" action="<?php echo $app->urlFor('users.update', array('id' => $user->id)) ?>" method="post">
  <label for="user-fullname" style="margin-right: 20px">Fullname</label>
  <input name="fullname" type="text" id="user-fullname" class="input-xlarge"
         value="<?php echo $user->fullname ?>">
  <button type="submit" class="btn btn-primary">Save</button>
</form>

<div class="page-header">
  <h4>Group membership</h4>
</div>
<div class="section">
  <form class="form-inline" action="<?php echo $app->urlFor('users.membership', array('id' => $user->id)) ?>" method="post">
    <label for="user-group" style="margin-right: 20px">Select group</label>
    <select name="group_id" id="user-group">
      <option value="">None</option>
    <?php foreach ($groups as $group): ?>
      <option value="<?php echo $group->id ?>" 
        <?php echo $user->is_member($group) ? 'selected' : '' ?>><?php echo $group->name ?></option>
    <?php endforeach ?>
    </select>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>

<div class="page-header">
  <h4>HTTP/HTTPS Rules</h4>
</div>
<div class="section">
  <!-- HTTP/HTTPS rules inherited from group -->
  <h5 class="muted">
    Rules inherited from group
    <?php if ($user->is_member()): ?>
      <a href="<?php echo $app->urlFor('groups.show', array('id' => $user->group_id)) ?>#http-rules"
         class="btn btn-mini" title="Edit rules"><i class="icon-edit"></i></a>
    <?php endif ?>
  </h5>
  <div class="section">
    <?php partial('rules/_http_list.phtml', array(
      'rules' => $http_group_rules,
      'rule_owner_type' => 'Group',
      'rule_owner_id' => $user->group_id,
      'readonly' => true,
      'disabled' => null
    )) ?>
  </div>
  <!-- HTTP/HTTPS rules for this user -->
  <h5 class="muted" style="margin-top: 20px;">
    Rules defined only for this user
    <?php if ($user->is_member()): ?> (inactive) <?php endif ?>
  </h5>
  <div class="section">
    <?php partial('rules/_http_list.phtml', array(
      'rules' => $http_rules,
      'rule_owner_type' => 'User',
      'rule_owner_id' => $user->id,
      'readonly' => $user->is_member() ? true : null,
      'disabled' => $user->is_member() ? true : null,
    )) ?>
  </div>
</div>

<div class="page-header">
  <h4>TCP/UDP Rules</h4>
</div>
<div class="section">
  <!-- TCP/UDP rules inherited from group -->
  <h5 class="muted">
    Rules inherited from group
    <?php if ($user->is_member()): ?>
      <a href="<?php echo $app->urlFor('groups.show', array('id' => $user->group_id)) ?>#tcp-rules"
         class="btn btn-mini" title="Edit rules"><i class="icon-edit"></i></a>
    <?php endif ?>
  </h5>
  <div class="section">
    <?php partial('rules/_tcp_list.phtml', array(
      'rules' => $tcp_group_rules,
      'rule_owner_type' => 'Group',
      'rule_owner_id' => $user->group_id,
      'readonly' => true,
      'disabled' => null
    )) ?>
  </div>
  <!-- TCP/UDP rules for this user -->
  <h5 class="muted" style="margin-top: 20px;">
    Rules defined only for this user
    <?php if ($user->is_member()): ?> (inactive) <?php endif ?>
  </h5>
  <div class="section">
    <?php partial('rules/_tcp_list.phtml', array(
      'rules' => $tcp_rules,
      'rule_owner_type' => 'User',
      'rule_owner_id' => $user->id,
      'readonly' => $user->is_member() ? true : null,
      'disabled' => $user->is_member() ? true : null,
    )) ?>
  </div>
</div>

<div class="page-header">
  <h4>OpenVPN settings</h4>
</div>
<div class="section">
  <div class="section pull-left" style="margin: 0 60px 20px 0">
    <div class="btn-group">
      <button class="btn  dropdown-toggle" data-toggle="dropdown">
        <i class="icon-download-alt"></i> Download configuration
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <a href="<?php echo $app->urlFor('users.config', array('id' => $user->id, 'os' => 'win')) ?>">
             for Windows
          </a>
        </li>
        <li>
          <a href="<?php echo $app->urlFor('users.config', array('id' => $user->id, 'os' => 'osx')) ?>">
             for Mac OS X
          </a>
        </li>
        <li>
          <a href="<?php echo $app->urlFor('users.config', array('id' => $user->id, 'os' => 'lnx')) ?>">
             for Linux
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="section">
    <?php partial('users/_toggle_suspend.phtml', array('user' => $user)) ?>
  </div>
</div>
