<ul class="breadcrumb">
  <li><a href="<?php echo $app->urlFor('users') ?>">Users</a> <span class="divider">/</span></li>
  <li><a href="<?php echo $app->urlFor('users.show', array('id' => $user->id)) ?>"><?php echo $user->username ?></a></li>
</ul>

<h3><?php echo $user->username ?> (<?php echo $user->fullname ?>)</h3>

<form class="form-horizontal" action="<?php echo $app->urlFor('users.update', array('id' => $user->id)) ?>" method="post">
  <div class="control-group">
    <label class="control-label" for="user-fullname">Fullname</label>
    <div class="controls">
      <input name="fullname" type="text" id="user-fullname" value="<?php echo $user->fullname ?>">
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>


<h4>OpenVPN settings</h4>

<form class="form-horizontal" action="<?php echo $app->urlFor('users.toggle_suspend', array('id' => $user->id)) ?>" method="post">
  <div class="control-group">
    <div class="controls">
      <?php if ($user->suspended): ?>
        <button type="submit" class="btn btn-succes">Unsuspend</button>
      <?php else: ?>
        <button type="submit" class="btn btn-danger">Suspend</button>
      <?php endif ?>
    </div>
  </div>
</form>
