<ul class="breadcrumb">
  <li><a href="<?php echo $app->urlFor('groups') ?>">Groups</a> <span class="divider">/</span></li>
  <li><a href="<?php echo $app->urlFor('groups.new') ?>">Add group</a></li>
</ul>

<div class="page-header">
  <h3>Add new group</h3>
</div>

<form class="form-horizontal" action="<?php echo $app->urlFor('groups.create') ?>" method="post">
  <?php partial('groups/_form.phtml', array(
    'errors' => $errors,
    'group' => $group
  )) ?>
</form>
