<ul class="breadcrumb">
  <li><a href="<?php echo $app->urlFor('groups') ?>">Groups</a> <span class="divider">/</span></li>
  <li><a href="<?php echo $app->urlFor('groups.show', array('id' => $group->id)) ?>"><?php echo h($group->name) ?></a></li>
</ul>

<div class="page-header">
  <h3><?php echo h($group->name) ?></h3>
</div>

<form class="form-horizontal" action="<?php echo $app->urlFor('groups.update', array('id' => $group->id)) ?>" method="post">
  <?php partial('groups/_form.phtml', array(
    'errors' => $errors,
    'group' => $group
  )) ?>
</form>

<div class="page-header">
  <h4>HTTP/HTTPS Rules</h4>
</div>
<div class="section">
  <?php partial('rules/_http_list.phtml', array(
    'rules' => $http_rules,
    'rule_owner_type' => get_class($group),
    'rule_owner_id' => $group->id
  )) ?>
</div>

<div class="page-header">
  <h4>TCP/UDP Rules</h4>
</div>
<div class="section">
  <?php partial('rules/_tcp_list.phtml', array(
    'rules' => $tcp_rules,
    'rule_owner_type' => get_class($group),
    'rule_owner_id' => $group->id
  )) ?>
</div>

<div class="page-header">
  <h4>OpenVPN settings</h4>
</div>
<div class="section" id="openvpn-settings">
  <div class="section" style="margin-bottom: 15px">
    <?php partial('groups/_redirect_all_traffic.phtml', array('group' => $group)) ?>
  </div>
  <div class="section">
    <?php partial('groups/_default_policy.phtml', array('group' => $group)) ?>
  </div>
</div>

<div class="page-header">
  <h4>Members</h4>
</div>
<div class="section">
  <?php partial('users/_list.phtml', array('users' => $members)) ?>
</div>
