<!DOCTYPE html>
<html>
  <head>
    <title>OpenVPN Setup</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px;
      }
      .nav {
        margin-left: 60px;
      }
      .page-header {
        padding-bottom: 0;
        margin-bottom: 20px;
      }
      .page-header h4 {
        margin-top: 40px;
      }
      .sortable-handle {
        cursor: move
      }
      .form-inline {
        display: inline-block;
      }
      .rules li {
        margin-bottom: 10px;
      }
      .rules li form {
        margin-bottom: 0;
      }
      .input {
        display: inline-block;
      }
      .section {
        padding-left: 10px;
      }
    </style>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">OpenVPN Setup</a>
          <ul class="nav">
            <?php
              $menu = array(
                'users' => 'Users',
                'groups' => 'Groups',
                'password.edit' => 'Change password'
              );
            ?>
            <?php foreach ($menu as $key => $name): ?>
              <li class="<?php echo $section == $key ? 'active' : ''?>">
                <a href="<?php echo $app->urlFor($key) ?>"><?php echo $name ?></a>
              </li>
            <?php endforeach ?>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <?php foreach ($flash as $k => $msg): ?>
        <div class="flash alert alert-<?php echo $k ?>">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <?php echo $msg ?>
        </div>
      <?php endforeach ?>

      <?php echo $__content__ ?>
    </div>

    <script src="/js/jquery-1.9.1.min.js"></script>
    <script src="/js/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/app.js"></script>
  </body>
</html>
