<div class="page-header">
  <h3>Change password</h3>
</div>

<?php partial('_form_errors.phtml', array('errors' => $errors)) ?>

<form class="form-horizontal" action="<?php echo $app->urlFor('password.update') ?>" 
      method="post">
  <div class="control-group">
    <label class="control-label" for="password">New password</label>
    <div class="controls">
      <input name="password" type="password" id="password"  class="input-xlarge"
        value="<?php echo $password ?>"
        required>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="password-confirm">Confirmation</label>
    <div class="controls">
      <input name="confirmation" type="password" id="password-confirm"  class="input-xlarge"
        value="<?php echo $confirmation ?>"
        required>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>
